name: farmsys
description: Farmland Mapping.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan:
  qr_flutter:
  flutter_vector_icons:
  cached_network_image: ^2.2.0+1
  flutter_custom_clippers: ^1.1.1
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  intro_views_flutter: ^2.8.1
  share: ^0.6.4+3
  url_launcher: ^5.5.0
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.15.4
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  provider: ^4.0.4
  http: ^0.12.0
  geolocator: ^6.1.13
  vector_math: ^2.0.8
  flutter_spinkit: ^4.0.0
  flutter_launcher_icons: "^0.7.0"
  sqflite:
  path:
  path_provider:

  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_automation: null

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
